#target for compiling the source files
#compile:
sort_atoms:
	g++ -std=c++11 sort_atoms.cpp -o sort_atoms

molecule:
	g++ -std=c++11 molecule.cpp -o molecule

#target for running the resulting binaries
run:
	./sort_atoms
	./molecule

clean:
	rm -f sort_atoms molecule

